### ISSUE TITLE
Improve prebackup pod management

### ISSUE THREAD

**Issue by Kidswiss** [k8up-io/k8up#137]
## Summary

**As** a k8up developer
**I don't want** to handle the prebackup pod readiness in the operator
**So that** we can get rid of the complicated asynchronous prebackup pod handling

## Context

The backup execution is currently much more complex than the other ones. The main reason for this is, that the backups are handled asynchronously via a go-routine. The reason for this is, that the actual backup job needs to wait to be applied until the prebackup pods are ready. And it can take quite a while until the pods are running. Blocking during that time could result in a reconcile congestion when multiple backups start at the same time.

## Out of Scope

* List aspects that are explicitly not part of this feature

## Further links

* [Asynch backup trigger](https://github.com/vshn/k8up/blob/master/executor/backup.go#L76)

## Acceptance criteria

*Given* a backup with prebackpods
*When* the operator triggers it
*Then* it won't do it asynchronously

## Implementation Ideas

* We could tag the pre-backup pods and then handle the waiting logic in [wrestic](https://github.com/vshn/wrestic). The cleanup still has to be done by the operator with the observer callback. But we could just start everything at the same time and then wrestic will wait until the prebackup pods are running. With that we can get rid of the go-routine

**Comment by ccremer** [comment]
Are there any hard objections against executing prebackup pods as Kubernetes Jobs? We already have a Job controller that watches Job for their successes.

Now that we have conditions, backups can wait asynchronously until prebackup pods are finished. Example scenario:

1. Reconcile backup
  * Detect PrebackupPods and create Jobs for them.
  * Set condition to wait for prebackup pods (already implemented today)
  * Exit reconcile, don't start the actual backup yet (because the condition to wait for prebackup pod has been set)
2. Reconcile Jobs
  * Watch until prebackup pods succeed
  * If finished, update the Backup conditions that prebackup pods succeeded
3. Reconcile Backup again
  * Now that the condition is set, continue with regular restic backup.

This would get rid of the go routines, as well as the separate kubernetes client just for the watches. This separate k8s client just for the watcher bites us time and time again and makes testing very hard. (see #341 )

**Comment by ccremer** [comment]
Actually, the way users are expected to configure prebackup pods (long running pod, then some Backupcommand exec's into it), moving to Jobs would be kind of a breaking change, right?

in that case it might be easier to keep a deployment (or just replicasets instead), but watch for deployments with a label predicate or so. Still, reacting upon the deployment's/replicaset's conditions could be done asynchronously, and so can prebackups

**Comment by Kidswiss** [comment]
That sounds like a good idea.

As you correctly realised the prebackuppods don't actually finish before wrestic is run. They have to be running until the backup is finished. So we'd only have to wait for the condition that they are running instead of succeeded.

**Comment by Kidswiss** [comment]
This issue here is about the waiting logic only. So we can close here.

Discussions about the exec itself are located here: https://github.com/k8up-io/k8up/issues/585
